# Renders a single SLC template. The template body is on $TEMPLATE, the merged
# template_contribution map (YAML) on $VARS, and the source file name on
# $TEMPLATE_NAME. Contribution names become top-level template variables.

from jinja2 import Environment, BaseLoader, select_autoescape
import yaml
import os
import sys

template_str = os.environ.get('TEMPLATE')
vars_str = os.environ.get('VARS')
template_name = os.environ.get('TEMPLATE_NAME', 'template')

if vars_str is None:
    print("VARS environment variable is not set", file=sys.stderr)
    sys.exit(1)

if template_str is None:
    print("TEMPLATE environment variable is not set", file=sys.stderr)
    sys.exit(1)

# The banner the built-in autogenerated_file/autogenerated_c_file globals expand
# to. Naming the source template is part of the SLC-defined behavior.
_BANNER_LINES = [
    "This file is autogenerated by Silicon Labs SLC.",
    "The contents of this file will be replaced in their entirety upon regeneration.",
    "Source template file: " + template_name,
]


def line_prefix_suffix(value, prefix='', suffix=''):
    """Add prefix and suffix to each line of value (the SLC `format` filter)."""
    return "\n".join(prefix + line + suffix for line in str(value).split("\n"))


autogenerated_file = "\n".join(_BANNER_LINES)
autogenerated_c_file = line_prefix_suffix(autogenerated_file, prefix='// ', suffix='')

env = Environment(
    loader=BaseLoader,
    autoescape=select_autoescape(),
    # Preserve the template's trailing newline so generated file content is not
    # silently altered.
    keep_trailing_newline=True,
)

# `format` is applied to the banner text, e.g. `autogenerated_file | format(prefix='// ')`.
env.filters['format'] = line_prefix_suffix

# The banners are values (globals), referenced directly as `{{ autogenerated_c_file }}`.
env.globals['autogenerated_file'] = autogenerated_file
env.globals['autogenerated_c_file'] = autogenerated_c_file

try:
    vars = yaml.safe_load(vars_str)
except yaml.YAMLError as e:
    print(e, file=sys.stderr)
    sys.exit(1)

if vars is None:
    vars = {}

template = env.from_string(template_str)
sys.stdout.write(template.render(vars))
