# Helper script to get around the missing support for modifying template locals in minijinja

from jinja2 import Environment, BaseLoader, select_autoescape
import yaml
import os

template_str = os.environ['TEMPLATE']
vars_str = os.environ['VARS']

if vars_str is None:
	print("VARS environment variable is not set")
	exit(1)

if template_str is None:
	print("TEMPLATE environment variable is not set")
	exit(1)

def autogenerated_file(value):
	return ""

def autogenerated_c_file(value):
	return ""

def format(value, **kwargs):
	return value

env = Environment(
	loader=BaseLoader,
	autoescape=select_autoescape()
)

env.filters['autogenerated_file'] = autogenerated_file
env.filters['autogenerated_c_file'] = autogenerated_c_file
env.filters['format'] = format

try:
	vars = yaml.safe_load(vars_str)
except yaml.YAMLError as e:
	print(e)
	exit(1)

template = env.from_string(template_str)
print(template.render(vars))